"""create decisions table

Revision ID: 13105909b908
Revises: 
Create Date: 2026-08-26 00:47:36.156616

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13105909b908'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('risk_class', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('application', sa.JSON(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('defaulted', sa.Integer(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_defaulted'), ['defaulted'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_model_version'), ['model_version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_model_version'))
        batch_op.drop_index(batch_op.f('ix_decisions_defaulted'))
        batch_op.drop_index(batch_op.f('ix_decisions_created_at'))

    op.drop_table('decisions')
    # ### end Alembic commands ###
